version: '3'
services:      
  eureka-naming-server:
    restart: on-failure
    container_name: eureka-naming-server
    image: vimal8193/eureka-naming-server:1.0
    expose:
      - "8761"
    ports:
      - 8761:8761
   
  orders-app:
    restart: on-failure
    image: vimal8193/orders-app:1.0
    expose:
      - "8081"
    ports:
      - 8081:8081
    depends_on:
      - eureka-naming-server